name: Executar diariamente

on:
  schedule:
    - cron: '30 23 * * *' # Define o agendamento para meia-noite (00:00) diariamente UTC

jobs:
  run_script:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout do código
      uses: actions/checkout@v2

    - name: Configurar Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.10' # Substitua 'x' pela versão do Python que seu script requer

    - name: Executar o script
      run: python https://raw.githubusercontent.com/RafaellSanchez/api-bolsa/workspaces/api-bolsa/code/api_bolsa.py
