name: Executar Script Python

on:
  push:
    branches:
      - main

jobs:
  run-python-script:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout do repositório
        uses: actions/checkout@v2

      - name: Configurar ambiente Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.10'  # Substitua '3.x' pela versão do Python que você deseja usar

      - name: Instalar dependências Python (se necessário)
        run: |
          python -m pip install --upgrade pip
          pip install pandas

      - name: Executar script Python
        run: python $GITHUB_WORKSPACE/workspaces/api-bolsa/.github/scheduler/teste_scheduler.py

      - name: Salvar resultados
        run: cp -r resultados/* $GITHUB_WORKSPACE/workspaces/api-bolsa/.github/scheduler/
