name: Executar Script Python

on:
  push:
    branches:
      - main

jobs:
  run-python-script:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout do repositório
        uses: actions/checkout@v2

      - name: Conceder permissões de leitura ao arquivo
        run: chmod +r path_scheduler/Dados_BVSP_20231214_024249.txt

      - name: Configurar ambiente Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.10'  # Substitua '3.x' pela versão do Python que você deseja usar

      - name: Instalar dependências Python (se necessário)
        run: |
          python -m pip install --upgrade pip
          pip install pandas

      - name: Executar script Python
        run: python path_scheduler/teste_scheduler.py

      - name: Salvar resultados
        run: cp -r resultados/* path_scheduler/
