name: Executar diariamente teste

on:
  schedule:

    - cron: '*/5 * * * *' # Define o agendamento para meia-noite (00:00) diariamente UTC

jobs:
  run_script:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout do código
        uses: actions/checkout@v2
        with:
          ref: 'main' # Especifica o branch que você deseja usar

      - name: Configurar Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.10' # Substitua 'x' pela versão do Python que seu script requer

      - name: Criar diretório de destino
        run: mkdir -p $GITHUB_WORKSPACE/teste/scheduler

